### ISSUE TITLE
WORKS ONLY ON BATMAN BEGINS NOT ON ANY OTHER MOVIE

### ISSUE THREAD

**Issue by arunsehgals** [yadavgaurav251/Context-Aware-Recommender#15]
can you please help it works only on batman begins not on any other movie

**Comment by yadavgaurav251** [comment]
I think the issue you are having is you are using movies that are not part of the database, due to which the system crashes. So I suggest you go through the [Movie Dataset](https://github.com/yadavgaurav251/Context-Aware-Recommender/blob/main/Dataset/movies_metadata.csv) and pick movies from there. You could try some more movies like Air Force One, Iron Man, True Lies.
